version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:8080"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - web

